### ISSUE TITLE
undeclared identifier "PDISPATCHERQUEUECONTROLLER"

### ISSUE THREAD

**Issue by xhybb** [xxoo/av_media_player#1]
windows\av_media_player_plugin.cpp(63,5): error C2065: undeclared identifier "PDISPATCHERQUEUECONTROLLER"

**Comment by xxoo** [comment]
`PDISPATCHERQUEUECONTROLLER` is defined in DispatcherQueue.h which is included in av_media_player_plugin.cpp
Maybe your windows sdk is too old or there is something missing in your system environment
Please try to install the latest Visual Studio and make sure **Desktop development with C++** is checked

**Comment by xhybb** [comment]
OK
