### ISSUE TITLE
Fatal error: Unable to bridge NSNumber to Float. (macos)

### ISSUE THREAD

**Issue by TheBilalJaved** [xxoo/av_media_player#11]
i am developing a macos app but when i try to change volume app crashes and show the error "Foundation/NSNumber.swift:478: Fatal error: Unable to bridge NSNumber to Float"

**Comment by xxoo** [comment]
confirmed

**Comment by xxoo** [comment]
@TheBilalJaved 
Thanks for reporting
This issue is fixed by now. Please upgrade to 1.1.4 and try again

**Comment by TheBilalJaved** [comment]
its working now thanks
