### ISSUE TITLE
Callbacks to track position and others

### ISSUE THREAD

**Issue by michalss** [xxoo/av_media_player#7]
Can you please also add callback to all possible events like position, length etc...?

this is also very important feature.. Without this u can't track the media progress. :) It has a valid point since you wanna use trakt or similar services for example..

**Comment by xxoo** [comment]
Most properties of av_media_player are instances of `ValueNotifier`. You may call `addListener` on these properties.
Please read [api documents](https://pub.dev/documentation/av_media_player/latest/player/AvMediaPlayer/position.html) or refer to main_advanced.dart in the example
