### ISSUE TITLE
[QUESTION] Encrypted video header

### ISSUE THREAD

**Issue by michalss** [xxoo/av_media_player#8]
HI,

Im facing to a huge issue here. I woud like to ask if there is any option to implement a function where i can play in players a video file with encrypted header. Where i did the encryption and im holding the decryption key? For this solution on Win,Linux and Android with native players, i would even pay a lot of money. :) Facing the isue that before video upload, need to encrypt the header first. Or is there any better solution how to prevent the server owner to check the content, but file would be still playable?

thx and regards

**Comment by xxoo** [comment]
In that case I would suggest you to serve a local http proxy in the app. Then decrypt the file in the proxy.
So you would be able to use a new url to open the source, like `http://127.0.0.1:8080/https://server.com/path/to/file`
